server:
  port: 10008
spring:
  application:
    name: seata-order-micro-service
  cloud:
    alibaba:
      seata:
        #指定事务组名，需要和seata-server中的对应 seata/config/file.conf
        tx-service-group: hspedu_order_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848 #指定nacos server地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/storage_micro_service
    url: jdbc:mysql://localhost:3306/order_micro_service?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hsp
#配置seata日志输出
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml